name = "hyprTwoPanePersistent"
description = "XMonad-style TwoPanePersistent layout"
author = "you"
version = "1.0"

[[plugins]]
name = "hyprTwoPanePersistent"
description = "TwoPanePersistent layout"
output = "libhyprTwoPanePersistent.so"
build =  ["cmake -B build -DCMAKE_BUILD_TYPE=Release", "cmake --build build"]
